cloudify-cosmo/cloudify-cli

cloudify_cli/bootstrap/tasks.py

added retry to container run execution since the services container sporadically fails to mount the data container volumes. This also required adding a validation so that the bootstrap process would not kill containers that were not started by it.

CFY-1910 added retry to container run execution and validation that does not exist prior to bootstapping.

---

cloudify_cli/commands/version.py

* Printing the cfy --version result to stdout.
* Manager version is printed when running cfy --version.

CFY-2773 and CFY-4493

---

packaging/windows/packaging/create_install_wizard.iss
packaging/windows/provision.sh

this doesn't include the part where cloudify cli shouldn't expect a virtualenv

CFY-4761 - windows cli embedded python

---

cloudify_cli/commands/use.py
cloudify_cli/commands/version.py
cloudify_cli/tests/commands/test_cli_command.py
cloudify_cli/tests/test_secured_get_rest_client.py
cloudify_cli/utils.py

Reverts cloudify-cosmo/cloudify-cli#306

Revert "CFY-5071 Version compatibility between Cloudify Manager and CLI tool …"

---

cloudify_cli/commands/__init__.py
cloudify_cli/commands/upgrade.py
cloudify_cli/config/parser_config.py
cloudify_cli/ssh.py
cloudify_cli/tests/commands/test_cli_command.py
cloudify_cli/tests/commands/test_upgrade.py
tox.ini

CFY-4954 add cli manager upgrade command

CFY-4954 added cli command

---

cloudify_cli/commands/agents.py

.join() on a thread uses a lock that cannot be interrupted by
signals. Instead, use the "while True: poll(); sleep()" pattern
to allow the cli to exit on user ctrl+c

CFY-5285 Handle SIGINT gracefully in `cfy agents install`

---

cloudify_cli/commands/node_instances.py

Errors other than 404 are no longer hidden

CFY-5642 `node-instances list`: report errors correctly

---

cloudify_cli/bootstrap/bootstrap.py
cloudify_cli/commands/bootstrap.py
cloudify_cli/commands/profiles.py
cloudify_cli/commands/ssh.py
cloudify_cli/env.py
cloudify_cli/tests/test_env.py

A few other minor changes and fixes

Fixed cfy use issue with custom ssh port

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/events.py
cloudify_cli/commands/executions.py
cloudify_cli/commands/groups.py
cloudify_cli/commands/use.py
cloudify_cli/commands/workflows.py
cloudify_cli/tests/commands/test_events.py
cloudify_cli/tests/commands/test_groups.py
cloudify_cli/tests/commands/test_workflows.py

Reverts cloudify-cosmo/cloudify-cli#429

Revert "CFY-5872 Fix CLI inconsistencies"

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/blueprints.py
cloudify_cli/commands/deployments.py
cloudify_cli/commands/plugins.py
cloudify_cli/commands/snapshots.py
cloudify_cli/tests/commands/test_teardown.py
cloudify_cli/tests/commands/test_use.py
cloudify_cli/tests/commands/test_users.py

Add/remove permissions, private resources

CFY-6096 Add resource permissions API

---

cloudify_cli/commands/tenants.py
cloudify_cli/commands/user_groups.py
cloudify_cli/utils.py

This includes:
* add/remove user from tenant
* add/remove user-group from tenant
* add/remove user from user-group

CFY-6112 Handle gracefully idempotent commands in the CLI

---

cloudify_cli/cli/cfy.py
cloudify_cli/tests/commands/test_users.py

- The password can no longer be empty
- The password has a maximum (256) and minimum (5) length

CFY-6466 Add basic password validations

---

cloudify_cli/execution_events_fetcher.py

In cloudify-cosmo/cloudify-manager#787 when the event data structure was updated to be flat, a problem was introduced because some other parts of the code, in particular `cloudify.event.Event` still expects some other data structure.
What this PR does is transform the data structure received from the API that to the one that was received in the past to avoid problems.

CFY-6648 Map event data structure to what `cloudify.event.Event` expects

---

cloudify_cli/commands/profiles.py

CFY-6934 Use `is not None` for checking the response

---

cloudify_cli/commands/cluster.py

This allows to show each checked service separately to the user,
which will greatly help debugging.

Add check details to the `cluster nodes list` command

---

packaging/windows/provision.sh

This reverts commit 71a17d0daf00e83011d03fb6b3293b65a6855348.

Revert "CFY-7109 tmp"

---

cloudify_cli/commands/cluster.py

Use node name when removing nodes from profile

When removing a cluster node, remove it from profile correctly

---

packaging/linux/provision.sh
packaging/omnibus/config/projects/cloudify.rb
packaging/omnibus/config/software/cloudify-manager-blueprints.rb

This reverts commit 32f4655827892813300b644be098d40a59dd7ad5.

Revert "add-osx-support (#654)"

---

cloudify_cli/commands/profiles.py

Similar to how `cfy profiles set` has it, `use` can get it as well.
This allows creating a profile without successfully contacting
the manager, which will be useful if we need to create a profile
for a manager that isn't created yet, or that is broken and not
responding (in which case we need a profile to teardown).
`cfy profiles use --skip-credentials-validation` will still try
to contact the manager if it's possible, but ignore any errors.
There are three requests being made during the course of
`cfy profiles use`:
- to figure out whether to use http or https - if the manager isn't
available and the flag is set, we default to http
- a status call in `_assert_manager_available` - if the manager
isn't available and the flag is set, the exception is caught
- the _get_provider_context call …

CFY-7211 Add --skip-credentials-validation to `cfy profiles use`

---

cloudify_cli/commands/blueprints.py
cloudify_cli/commands/deployments.py
cloudify_cli/commands/executions.py
cloudify_cli/commands/node_instances.py
cloudify_cli/commands/nodes.py
cloudify_cli/commands/plugins.py
cloudify_cli/commands/secrets.py
cloudify_cli/commands/snapshots.py
cloudify_cli/constants.py
cloudify_cli/tests/commands/mocks.py
cloudify_cli/tests/commands/test_blueprints.py
cloudify_cli/tests/commands/test_deployments.py
cloudify_cli/tests/commands/test_plugins.py

The permission column is replaced with the resource_availability :
The user can sort the list however he likes :

CFY-7297 Replace the permission property in resources view with availability

---

cloudify_cli/cli/cfy.py
cloudify_cli/commands/tenants.py

This method allows updating the user-tenant relationship.
Requires: cloudify-cosmo/cloudify-rest-client#196

CFY-7350. Add tenants update-user method

---

cloudify_cli/commands/agents.py
cloudify_cli/commands/nodes.py

This is due to the changes in the rest client code

CFY-7698 Call nodes/node_instances list with explicit kwargs

---

cloudify_cli/commands/executions.py

`--include-logs` is the default since 4.0 or so.

Changed timeout message

---

cloudify_cli/commands/profiles.py

Unfortunately there is no way to pass certs for each cluster
node when enabling ssl dynamically using `ssl enable` so
we simply set `trust_all` for them.

CFY-7722 Mark cluster profiles https on `ssl enable`

---

cloudify_cli/cli/cfy.py
cloudify_cli/commands/deployments.py

CY-323 change workflow_id parameter's default in deployment update from update to none

CY-322 remove inputs_changed column from deployment history table

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/users.py
cloudify_cli/tests/commands/test_users.py

Also fixed the help msg of security role flag.

CY-383 : Adding the option to create a user and associating with a tenant and user role

---

cloudify_cli/commands/executions.py
cloudify_cli/tests/commands/test_executions.py

Added a new column to specific execution view (get command).

CY-381 : Adding execution end time in cli view

---

cloudify_cli/commands/tenants.py
cloudify_cli/commands/users.py

Also adding it to 'add user to tenant' command

CY-414 : Adding to log message the chosen tenant rule

---

cloudify_cli/commands/profiles.py
cloudify_cli/tests/commands/test_profiles.py

This reverts commit 35c591849edf9f3889acf98436e7543cc2bc8aca.

Revert "CY-506: pass SSL indication to validate_credentials (#851)"

---

cloudify_cli/config/config.py
cloudify_cli/tests/commands/test_blueprints.py
cloudify_cli/tests/resources/blueprints/bad_blueprint/blueprint_catalog.yaml

Adding prevention to validate blueprint catalog import ('blueprint:') locally.

CY-680: blueprint import

---

cloudify_cli/commands/deployments.py
cloudify_cli/main.py

to retrieve capabilities. The command is almost identical to
`cfy deployments outputs`, so the same code was reused.

CY-643 Add a `cfy deployments capabilities` command

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/executions.py
cloudify_cli/main.py

Frontend for the client.executions.resume call

Add missing `cfy executions resume`

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/sites.py
cloudify_cli/tests/commands/test_sites.py

* Change the location format from 2 parameters : latitude and longitude to
one location string "<latitude>,<longitude>" like "38.915645,-77.220796".

CY-1246 Change the format of the site's location

---

packaging/docker_builder/Dockerfile
packaging/linux/provision.sh

Replace deprecated rubygems options

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/deployments.py
cloudify_cli/commands/plugins.py
cloudify_cli/tests/commands/test_deployments.py
cloudify_cli/tests/commands/test_plugins.py

- Adds a flag the dont_update_plugins flag to deployment updates

CY-1060 Add plugins update commands

---

cloudify_cli/VERSION
setup.py

version - revert to master version

---

packaging/windows/packaging/create_install_wizard.iss

- Pre-creating the cli folder, due to it's name contains a dot in the first char
- Updating general info

CY-1657: fixing cli win installer

---

packaging/windows/packaging/create_install_wizard.iss

- Due to that, it caused failures in prev versions of win (2012)

Revert "CY-1657: fixing cli win installer"

---

cloudify_cli/cli/cfy.py
cloudify_cli/commands/cluster.py
cloudify_cli/commands/status.py
cloudify_cli/tests/commands/test_cluster.py

- The command needed to be updated for new cluster status implementation

CY-2037: updating cluster status command

---

cloudify_cli/commands/logs.py

status-reporter: moving the status reports location

---

cloudify_cli/commands/cluster.py

but with a warning to the user, because AIO is still a kind of a cluster

CY-2212: allowing to run cluster related commands on AIO

---

build.sh
packaging/linux/provision.sh

New one seems broken for some reason
Anyway let's just get rid of omnibus entirely
For now, this

Checkout an old commit of omnibus-software

---

cloudify_cli/VERSION
cloudify_cli/cli/cfy.py
cloudify_cli/env.py

Drop the VERSION file because it doesn't make sense to keep
the version number in 2 places.
Also, the 'edition' wasn't even used.

Get current version based on package version

---

cloudify_cli/blueprint.py
cloudify_cli/cli/cfy.py
cloudify_cli/commands/blueprints.py
cloudify_cli/commands/deployments.py
cloudify_cli/tests/commands/mocks.py
cloudify_cli/tests/test_env.py
cloudify_cli/utils.py

CY-2453 Py3 porting: import moves

---

cloudify_cli/commands/deployments.py
cloudify_cli/commands/profiles.py
cloudify_cli/inputs.py
cloudify_cli/logger.py
cloudify_cli/tests/commands/test_agents.py
cloudify_cli/tests/commands/test_deployments.py
cloudify_cli/tests/commands/test_events.py
cloudify_cli/tests/commands/test_executions.py
cloudify_cli/tests/commands/test_init.py
cloudify_cli/tests/commands/test_install.py
cloudify_cli/tests/commands/test_node_instances.py
cloudify_cli/tests/commands/test_uninstall.py
cloudify_cli/tests/test_env.py
cloudify_cli/tests/test_inputs.py
cloudify_cli/tests/test_multiple_local_profiles.py

Unittests: get rid of warnings

---

.circleci/py3fixers
cloudify_cli/commands/agents.py
cloudify_cli/commands/blueprints.py
cloudify_cli/commands/maintenance_mode.py
cloudify_cli/commands/nodes.py
cloudify_cli/commands/secrets.py
cloudify_cli/commands/tenants.py
cloudify_cli/commands/workflows.py
cloudify_cli/tests/commands/test_agents.py
cloudify_cli/tests/commands/test_deployments.py
cloudify_cli/tests/commands/test_events.py
cloudify_cli/tests/test_env.py
cloudify_cli/tests/test_multiple_local_profiles.py
cloudify_cli/utils.py

A few of the simple stage2 changes
No unicode changes yet

CY-2453 Py3 porting: stage2 changes

---

.circleci/config.yml
cloudify_cli/tests/commands/test_agents.py
cloudify_cli/utils.py

CY-2458 Run unittests on python 3

---

packaging/cloudify-cli.spec
packaging/debian/build.sh

See commits for the .spec and the .deb change

CY-2436 package filename changes

---

cloudify_cli/commands/agents.py

Can't iterate over that dict, need to make a copy, because we
use `del` to mutate the dict

agents install: copy tenants_to_deps keys

---

cloudify_cli/commands/workflows.py
cloudify_cli/tests/commands/test_deployments.py
cloudify_cli/tests/commands/test_workflows.py

Drop unused params in str.format calls

---

cloudify_cli/commands/plugins.py
cloudify_cli/prettytable.py
cloudify_cli/tests/cfy.py
cloudify_cli/tests/commands/test_plugins.py

Implement the command, and some tests.
Also, make some other code in that module better.

CY-3302 Implement `cfy plugins install`

---

cloudify_cli/env.py

CY-3640 ClusterClient: handle 204 responses

---

cloudify_cli/tests/resources/blueprints/bad_blueprint/blueprint_catalog.yaml
packaging/linux/provision.sh
setup.py

This reverts commit 022ea5b91a58c847c4b35ce4cfc19fb9db1a63c6.

Revert "Bump version"

---

jenkins/Jenkinsfile
jenkins/build-pod.yaml

Fix yaml file to pull resources correctly and use spot instance.
Fix jenkinsfile artifacts archival. two stages we're counting on each other with a certain folder, split those to prevent failures.

Fix spot usage

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/deployments.py

Adding the `--labels` flag to `cfy deployments create`.

RD-620 Add labels to deployments create command

---

cloudify_cli/commands/deployments.py

Adding the command `cfy deployments labels add [OPTIONS] LABELS_LIST DEPLOYMENT_ID`

Rd 618 Add labels add command

---

cloudify_cli/cli/cfy.py
cloudify_cli/commands/deployments.py

Adding the command `cfy deployments labels delete [OPTIONS] LABEL DEPLOYMENT_ID`

RD-619 Add labels delete command

---

setup.py

To keep the version in sync w/ cloudify-common.
See cloudify-cosmo/cloudify-common#602

Bump pyyaml to 5.3.1

---

cloudify_cli/commands/permissions.py
cloudify_cli/main.py

RD-968 Add a basic Permissions CRUD

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/deployments.py

RD-1199 Basic deployment groups CLI

---

cloudify_cli/commands/events.py
cloudify_cli/commands/executions.py
cloudify_cli/execution_events_fetcher.py
cloudify_cli/tests/test_env.py
cloudify_cli/utils.py

Nothing fancy just yet.
And yes, I did just copy wait_for_execution. Seems like the simplest way.

RD-1100 Basic execution groups cli

---

cloudify_cli/commands/blueprints.py
cloudify_cli/commands/deployments.py
cloudify_cli/labels_utils.py
cloudify_cli/tests/commands/test_blueprints.py
cloudify_cli/tests/commands/test_deployments.py

Adding labels to the blueprints CLI

RD-1460 blueprints CLI labels

---

cloudify_cli/cli/helptexts.py

* Update help text for plugins update's all_blueprints

RD-1432 Clarify plugins update all-blueprints option

---

cloudify_cli/cli/helptexts.py

Co-authored-by: Lukasz Maksymczuk <tehasdf@users.noreply.github.com>

Update helptext for the `--force` in plugin update (#1189)

---

cloudify_cli/cli/cfy.py
cloudify_cli/commands/profiles.py
cloudify_cli/tests/commands/test_profiles.py

`if ssl is None` is not enough for when the setting can be
'on' or 'off'

Make sure `cfy prof set --ssl off` actually disables ssl

---

cloudify_cli/commands/blueprints.py
cloudify_cli/commands/deployments.py
cloudify_cli/labels_utils.py
cloudify_cli/tests/commands/test_deployments.py

Just the new commands, and an elif branch in the utils to handle
the groups, next to the other elif branches. Very trivial.

RD-1317 Labels handling for dep-groups

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/deployments.py

Delete a group, together with all deployments in the group.

RD-1810 Bulk deployments delete

---

cloudify_cli/commands/events.py

Allow listing events also by execution group (not only execution id)

RD-1418 cfy event list -g execution_group_id

---

cloudify_cli/commands/deployments.py

Update all deployments in a group. Yes, starting an exec-group is how
it works.
It was implemented in cloudify-cosmo/cloudify-manager#2913

RD-1816 Add `cfy dep groups update-deployments`

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/deployments.py

Implementation of the `cfy deployments groups extend --into-environments`

RD-2060 Deployment group extend into environments

---

cloudify_cli/commands/plugins.py

As the whole docstring is presented as a part of the usage help text for
the command, it sholud not be too technical and detailed.

RD-1425 Clean up plug update usage help text

---

cloudify_cli/commands/logs.py

This Fix added in order to allow generate logs archives based on the host ip + node type instead of depending on profile manager ip. Moreover, it adds support to validate if both ssh_user & ssh_user are set before downloading logs

RD-2283 Fix cfy logs download for 3 nodes cluster

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/profiles.py
cloudify_cli/tests/commands/test_profiles.py

description here https://github.com/cloudify-cosmo/cloudify-manager-install/pull/1166

Fix container restart

---

cloudify_cli/commands/config.py
cloudify_cli/inputs.py

CYBL-1132 Clarify update config helptext

---

cloudify_cli/commands/deployments.py
cloudify_cli/tests/commands/constants.py
cloudify_cli/tests/commands/test_deployments.py

RD-2616 Drop support for dep update based on a bluerprint

---

cloudify_cli/utils.py

Wait for upload_blueprint execution creation for maximum of about 5
seconds (0ms -> 100ms -> 200ms -> ... -> 900ms).  Otherwise sometimes
our CLI broke.

RD-3156 Wait for the upload_blueprint execution creation

---

setup.py

similar to what we did in c-manager and c-premium

Add cffi requirement

---

cloudify_cli/commands/node_instances.py

With a hasattr for back-compat with restclients who don't have it.

RD-3673 Display system_properties in `cfy node-insta get`

---

cloudify_cli/commands/plugins.py

Implementing three actions: list, add and delete for plugins' resource tags.

RD-4363 resource-tags manipulation

---

cloudify_cli/commands/nodes.py

Only display them in json/extended, because that's the only way
this will ever fit on screen.

RD-4612 Nodes list: add drifted/unavailable counts

---

cloudify_cli/commands/executions.py

RD-4923 Operations list: print out manager/agent name

---

cloudify_cli/cli/cfy.py
cloudify_cli/commands/plugins.py
cloudify_cli/config/config.py

Follow up of https://github.com/cloudify-cosmo/cloudify-common/pull/1057

RD-4930 Enable multiple yaml files for a plugin

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/events.py
cloudify_cli/commands/executions.py
cloudify_cli/logger.py
cloudify_cli/tests/commands/mocks.py
cloudify_cli/tests/commands/test_executions.py
cloudify_cli/tests/test_env.py

Show the acting manager/agent name.
Requires cloudify-cosmo/cloudify-common#1060

RD-4923 Add --with-worker-names

---

cloudify_cli/commands/deployments.py

Like `cfy dep li`, but only shows the various statuses. It's useful
for an overview of the system.

RD-4408 Add `cfy deployments status-list`

---

cloudify_cli/commands/audit_log.py

https://click.palletsprojects.com/en/8.1.x/advanced/#parameter-modifications

RD-6131 Click's callback take three arguments

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/node_instances.py
cloudify_cli/commands/nodes.py

I'm a bit tired of having to use the restclient to do this :)
Also, node-instances list don't have this feature. Only nodes get, nodes list, NI get.

RD-6446 Add `--evaluate-functions`

---

jenkins/Jenkinsfile
jenkins/build-pod.yaml

Hopefully with this, CI can run at all.

Update jenkins agent version

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/secrets.py

We apparently want to add it even if the check fails in case someone is adding the provider before it is up, so let's allow them to cleanly do that.

RD-6768 Allow skipping secrets provider conn check

---

cloudify_cli/commands/audit_log.py

```
[root@0df8f19e9074 ~]# cfy audit list
Listing audit log entries...
AuditLogs:
+-----------+----------------------------------------------------------------+--------------+--------------------------------------+-------------------------+
| operation |                           ref_object                           | creator_name |             execution_id             |        created_at       |
+-----------+----------------------------------------------------------------+--------------+--------------------------------------+-------------------------+
|   create  |                  default_tenant:blueprints:bp                  |    admin     |                                      | 2023-03-28 13:06:00.599 |
|   update  |        usage_collector:17751f47e76e4ef1a798eb0c1470b51b        | …
```

RD-7142 Add ref_identifier and id fields to audit_log

---

cloudify_cli/async_commands/audit_log.py

This is a cherry-pick of https://github.com/cloudify-cosmo/cloudify-cli/pull/1472

Wrap aiohttp ClientError with CloudifyCliError

---

packaging/cloudify-cli.spec
packaging/debian/build.sh

We've already built this tgz so let's use it...

RD-6984 Use a separate python .tgz for the CLI rpm/deb

---

packaging/windows/win_cli_builder.ps1

RND-681 windows build: rename python36.zip to python311.zip
