cloudify-cosmo/cloudify-cli

cloudify_cli/tests/commands/test_local.py

There is no need to use --install-plugins flag to test the missing modules. 
The local init command fails if the modules are not ignored, as it should, even without using the flag.

CFY-1747 removed the --install-plugins flag from test.

---

cloudify_cli/config/parser_config.py

deployments create
reason: `assert deployment_id` in DeploymentsClient.create
deployments delete
reason: `assert deployment_id` in DeploymentsClient.delete
deployments outputs
reason: `assert deployment_id` in DeploymentOutputsClient.get
executions start
reason: `assert deployment_id` in ExecutionsClient.start
workflows get
reason: `assert deployment_id` in DeploymentsClient.get
workflows list
reason: `assert deployment_id` in DeploymentsClient.get

CFY-4759 make some `deployment_id` arguments be required by the cli

---

cloudify_cli/execution_events_fetcher.py
cloudify_cli/tests/commands/test_deployments.py
cloudify_cli/tests/commands/test_events.py
cloudify_cli/tests/test_execution_events_fetcher.py

Running an execution like `cfy executions start` only waits until
the execution's status changes to terminated (or failed, cancelled).
This makes it so the cli also waits for a workflow_succeeded (or failed,
cancelled) event, not just for the status change.

CFY-4393 wait for a finished event when running an execution

---

cloudify_cli/common.py

Don't use the pip that is on the PATH: it will be the system-global
pip if we're running `venv/bin/cfy` directly, without activating the
virtualenv.
Instead, use `sys.executable` to run `python -m pip` with the
virtualenv-local python.

CFY-5308 Use a local pip when installing plugins

---

cloudify_cli/cli.py

cfy argparse metavars were formatted using the spacing of the
longest cfy command length. while this is true for sub-commands
that is not the case for the metavars that make the output of cfy
on invalid output as out-of-indentation

CFY-5496 remove spacing for cfy metavars

---

cloudify_cli/commands/__init__.py

It should remove the comment, which is " # import cfy sub commands ". I think that they are also direct commands for cfy.
@idanmo  PTAL.
Thanks!

Remove the incorrect comment

---

cloudify_cli/main.py

This fix is required so that loggers can be properly configured to DEBUG when running commands with `-vvv`. Otherwise, the loggers dict is not populated yet when the verbose configuration occurs

call configure loggers on startup

---

cloudify_cli/env.py
setup.py

The old one would remove trailing padding `=`'s, which caused problems for flask-security

CFY-5948 Replace base64 encode function

---

cloudify_cli/commands/deployments.py

Remove redundant `DEPLOYMENT_ID` from `cfy deployments create` command.
There is both and option and an argument with the same purpose, so the
argument can be safely removed.

CFY-6003 Remove deployment argument

---

cloudify_cli/commands/deployments.py
cloudify_cli/tests/commands/test_deployments.py

In this PR the `cfy deployments create` command argument parsing is updated to use an argument for the `deployment_id` instead of an option.

CFY-6003 Use optional argument instead of option

---

cloudify_cli/blueprint.py
cloudify_cli/commands/install.py
cloudify_cli/tests/test_blueprint.py
cloudify_cli/tests/test_env.py

In this PR, the code that downloads the blueprint file when a URL or a github repo is passed as argument is only used when installed the blueprint locally. When the blueprint is to be uploaded to the manager, the URL is passed directly and the manager is expected to download the blueprint file itself.
What concerns me is that there's a `blueprint_filename` parameter that is used to specify when the blueprint file in an archive file is not the default one and that information is lost when the URL is passed to the manager. Any comment/suggestion about this?

CFY-6006. Pass blueprint url to manager

---

cloudify_cli/commands/blueprints.py

When a URL is passed, the `client.blueprints.upload` call is no longer
useful because it expects a file to be passed. The right API call in
this case is `client.blueprints.publish_archive`.

CFY-6006 Use publish_archive instead of upload when a url is passed

---

cloudify_cli/commands/teardown.py
cloudify_cli/tests/commands/test_teardown.py

In this PR, the `use` command that was called directly from the `teardown` one is now called using `ctxt.invoke` to avoid parsing arguments from the command line.
Note: I had to include 2832295 in this branch make the test cases pass. However, the commit is not in the `master` branch. I believe the commit should be pushed to the `master` branch before this branch, so that the diff in this branch contains only the changes related to the issue that has been fixed.

CFY-6005. Fix use callback invocation

---

cloudify_cli/bootstrap/bootstrap.py

This PR fixes Cloudify's CLI suggested solutions for a plugin import error on bootstrap.
The suggestions were adjusted to Cloudify's 4.0 CLI.

CFY-6271 fix bootstrap import error possbile solutions

---

cloudify_cli/commands/snapshots.py

In this PR, the `cfy snapshot list` command is fixed. The problem was that a trailing comma was missing in the list of columns for the table to print in the output.

CFY-6280 Fix snapshot list command

---

cloudify_cli/commands/tenants.py

The tenant name argument would get implanted in the client headers

CFY-6343 Fix a bug in tenants get/delete

---

cloudify_cli/commands/tenants.py

The tenant name argument would get implanted in the client headers

CFY-6343 Fix a bug in tenants add/remove users/user-groups

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/tenants.py
cloudify_cli/commands/user_groups.py
cloudify_cli/commands/users.py

When running `cfy tenants/users/user-groups list` the default behavior would be to show the count of connected models (e.g. if running `cfy tenants list` and some tenant has 3 users and 2 groups connected to it, the output would be to only show those numbers instead of the actual users/groups connected).
It is still possible to get the old behavior by adding the `--get-data` flag.

CFY-6412 Show only counts of users/tenants/groups when listing

---

cloudify_cli/env.py

For the failover to work properly, we need to timeout requests
and retry with the other nodes in the cluster

Use a timeout by default with a cluster client

---

cloudify_cli/tests/commands/test_deployments.py
cloudify_cli/tests/commands/test_events.py
cloudify_cli/tests/test_env.py

In this PR, the test cases that were broken in #572 have been fixed by updating mock data to use the expected format.

CFY-6648 Generate mock events following the expected data structure

---

cloudify_cli/execution_events_fetcher.py
cloudify_cli/tests/commands/test_deployments.py
cloudify_cli/tests/commands/test_events.py
cloudify_cli/tests/test_env.py

The database field is called `error_causes`, but the implementation that
use the AMQP event structure expect the `task_error_causes` field.
Related:  cloudify-cosmo/cloudify-manager-blueprints#540

CFY-6479 Map error_causes to task_error_causes

---

cloudify_cli/commands/executions.py

The new error message should make clear what flags to use to avoid
getting stuck with a deployment that cannot be uninstalled.

CFY-6725. Update uninstall workflow error message

---

cloudify_cli/env.py
cloudify_cli/tests/test_env.py

In this PR, multiple local blueprints is activated by default, meaning that it's possible to orchestrate locally multiple blueprints without having to connect the client to a manager.

CFY 6722. Allow multiple local blueprints by default

---

cloudify_cli/local.py
cloudify_cli/tests/__init__.py
cloudify_cli/tests/commands/test_executions.py
cloudify_cli/tests/commands/test_init.py
cloudify_cli/tests/commands/test_node_instances.py
cloudify_cli/tests/commands/test_uninstall.py
cloudify_cli/tests/test_env.py
cloudify_cli/tests/test_multiple_local_profiles.py

In this PR, a few test cases have been added to verify that the multiple local profiles feature works as expected.
In addition to this, the testing environment is updated to enable multiple local profiles by default to match the current implementation. This requires to update test cases to add a missing blueprint parameter that wasn't needed when the default was to use a single local profile.

CFY-6836. Add multiple local profiles test cases

---

cloudify_cli/commands/profiles.py
cloudify_cli/tests/commands/test_use.py

In `cfy profiles use`, if we didn't pass --manager-username on the
commandline, the get_rest_client call inside _get_rest_port_and_protocol
would pass None, so get_rest_client would use the credentials from the
profile.
...but that would be the PREVIOUSLY active profile (because the one
we are currently activating, haven't been activated just yet), so
a completely different manager, so of course the credentials would
be wrong.
And anyway, that request is run on HTTP, unencrypted, so let's not
send the credentials there - the user chose to use HTTPS to protect
their credentials

CFY-6934 Don't use profile creds for the "is manager secured" request

---

cloudify_cli/commands/profiles.py
cloudify_cli/env.py

`set_active_profile`, instead of just writing to the active.profile
file, will now set `env.profile = active_profile` as well.
This is done using the global keyword so it is somewhat dirty, but we
are using the profile as a global after all.
This is because bootstrap creates and sets a new profile, so the rest
of bootstrap code should be able to use that profile. Specifically,
without this change, the get_rest_client call will still use the
previous (non-temp, whatever profile was active before) profile,
and if that previous active profile had a cluster, then it'll try
to use the cluster client.

CFY-6901 When setting the active profile, also set it in-process

---

cloudify_cli/commands/profiles.py

Pass `profile` explicitly to `get_rest_client`, so that there's no way
this uses the old profile anymore.

CFY-7048 Make `profiles use` don't use the old profile for httpscheck

---

cloudify_cli/env.py

Using rest_client.host isn't enough because that just shows the
original ip in a cluster profile. Instead, we want the ip of the
server that actually is active, and the rest client will update the
profile accordingly

CFY-6906 Use the profile manager_ip for cfy --version display

---

cloudify_cli/cli/cfy.py

set_cli_except_hook expects the verbosity value, it needs to be
passed down from set_verbosity_level via main.
Otherwise it's just lost.

CFY-7081 When setting verbosity, don't lose the value

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/cluster.py

Port of #524 
* CFY-6009 Pass inputs to start/join to allow configuration
* Add `cfy cluster nodes update`
* Change --inputs to --options
* Pretty print options
* YAML-style options in `cfy cluster nodes get`
* Change table header in `cluster nodes get`
* 'Node configuration' instead of 'Node options'

CFY-7103 Pass inputs to start/join to allow configuration

---

cloudify_cli/execution_events_fetcher.py

In this PR, the problem of logs out of order is fixed by using `reported_timestamp`
as the sort column instead of `timestamp` for the events retrieved by the CLI using the REST client.
Data flow analysis:
- the events were sent in the right order from the management worker to rabbitmq,
- were delivered by rabbitmq in the right order to logstash
- logstash was inserting them in the database in the right order
- the cli failed to get the events in the right order because sorting by `timestamp` just doesn't work when the events being considered have the same timestamp value since they are inserted by logstash into the database in the same batch.
Timestamp values explanation:
- `timestamp` is a value generated when an event is inserted into the database.
- `reported_timestamp` is generated …

CFY-7106 Fetch events sorted by reported timestamp by default

---

cloudify_cli/env.py

After sending a request to a node removed from the cluster - which
will of course fail - retry that request.

CFY-7145 ClusterHTTPClient: also retry requests sent to removed nodes

---

cloudify_cli/commands/dev.py

Also 'exec_globals' isn't always there

CFY-7130 Fix `cfy dev` typos

---

cloudify_cli/commands/cluster.py
cloudify_cli/commands/profiles.py
cloudify_cli/env.py

When we use `cfy cluster nodes remove`, all the relevant profiles are updated:
- all the profiles that are connected to that cluster remove 
node from their cluster list
- all the profiles for that node can remove their cluster list entirely
This allows (together with #665) to `cfy use` the profile of that node, which
will allow doing ssh-related tasks on it (eg. teardown).

CFY-7231 Remove from cluster removes from profile

---

cloudify_cli/bootstrap/bootstrap.py

This case may occur if the users provided networks in the bootstrap
inputs, but `default` was not one of them. Here we make sure that if
that's the case, we'll just put the default broker IP in there

CFY-7197 Fix the case where there would be no `default` network

---

cloudify_cli/commands/deployments.py
cloudify_cli/tests/commands/test_deployments.py

In case of missing input:
```
Unable to create deployment. Not all required inputs have been specified. Missing input(s): <comma-separated-list-of-inputs>
```
In case of unknown input:
```
Unable to create deployment, unknown input(s) were specified: <comma-separated-list-of-inputs>
```
The CLI exception itself is suppressed from the console log, but _is_ printed to the CLI log file.

CFY-6850: simplified error reporting when missing / unknown inputs are provided

---

.gitignore
cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/profiles.py
cloudify_cli/tests/commands/test_profiles.py
cloudify_cli/tests/commands/test_use.py

* Added `--secured` switch to `cfy profiles use`
* Removed dummy `status` request for the purpose of determining protocol & port
* Protocol is `https` if `--secured` is specified, `http` otherwise
* If `--rest-port` is provided, it is used. Otherwise, the port is `443` if the protocol is `https`, or `80` if the protocol is `http`.

CFY-7253: remove ssl redirect

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/tenants.py

In this PR, the `-r/--role` flag is used to the `cfy tenants add-user` command, so that the role value can be set in the CLI.
Requires: cloudify-cosmo/cloudify-rest-client#194

CFY-7350. Add role option to command

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/tenants.py

In this PR, the role option is added to the `cfy tenants add-user-group` command.

CFY-7373. Add group to tenant with role

---

cloudify_cli/cli/cfy.py
cloudify_cli/commands/tenants.py

This method allows updating the group-tenant relationship.
Requires: cloudify-cosmo/cloudify-rest-client#197

CFY-7373. Add tenants update-group method

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/tenants.py

In this PR, the role options for the `cfy tenants add-user/add-user-group` commands are refactored.

CFY-7373. Refactor role option

---

cloudify_cli/commands/agents.py
cloudify_cli/commands/ssh.py
cloudify_cli/commands/tenants.py

This is to be consistent since the add/remove commands are named
`add-user-group` and `remove-user-group`.

CFY-7373. Rename command from `update-group` to `update-user-group`

---

cloudify_cli/commands/tenants.py

For consistency they are now named `add/remove/update_user_group`
instead of just `add/remove/update_group`
Requires: cloudify-cosmo/cloudify-rest-client#200

CFY-7373. Update REST client command names

---

cloudify_cli/cli/cfy.py
cloudify_cli/commands/profiles.py
cloudify_cli/tests/commands/test_profiles.py

For already existing profiles, only switch to them, don't actually try
to get provider context, or update the profile.
currently, `cfy profiles use` has 3 modes of working:
1. create a new profile
2. switch profiles
3. switch profiles AND update the existing profile, 
eg `cfy profiles use existing.profile.ip --password updated_password`
This change gets rid of 3, so it is an error to pass any flags (like `--password`)
when using `cfy profiles use` with an already existing profile.

CFY-7439 cfy profiles use: only switch, don't update existing profiles

---

cloudify_cli/commands/teardown.py

This was related to the recovery process, which isn't supported
anymore.

CFY-7439 Don't update provider context in teardown

---

cloudify_cli/commands/profiles.py
cloudify_cli/tests/commands/test_profiles.py

Similar to how `cfy profiles set` allows setting things like the
REST cert and ssh params for a profile, `cfy profiles set-cluster`
allows setting those for a specific node in a cluster.
This means we can use the cli to set a different cert for every
cluster node.

CFY-7332 Add a command to `profiles set` for a specific cluster node

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/secrets.py

In this PR, the create secret command is updated to handle the upsert flag that is now supported by the REST API.
Requires: cloudify-cosmo/cloudify-rest-client#206

CFY-7562. Secret create update_if_exists

---

cloudify_cli/commands/cluster.py
cloudify_cli/tests/commands/test_cluster.py

Since we already download the nodes list in `cluster nodes list`,
we might as well also update the local profile (which required
a `cfy cluster update-profile` before).

CFY-7709 `cluster nodes list` also updates profile

---

cloudify_cli/config/config.py
cloudify_cli/tests/commands/test_blueprints.py
cloudify_cli/tests/resources/blueprints/bad_blueprint/plugin_repo.yaml

This blueprint can't be validated locally, instead it must be
uploaded to a manager.
Example:
```
Validating blueprint: bp.yaml
Error fetching plugin yaml: 'plugin:cloudify-openstack-plugin'
Blueprints using plugin repository imports can not be validated locally.
Possible solutions:
- Upload the blueprint to a Cloudify Manager
- Use an explicit URL to the plugin YAML file instead of a plugin repository `plugin:` import.
```

CFY-7801 Error message for using `plugin:` with `blueprint validate`

---

cloudify_cli/commands/cluster.py

If the request comes in at a time when the restservice/nginx is just
restarting, the error returned might not actually be a http-level
5xx error, but it might be a connection error instead (the rare
`Bad status line` exception).
This is expected during service restarts, and the CLI should keep
polling.

CFY-7900 _wait_for_cluster: also except ConnectionError

---

cloudify_cli/env.py

Setting the timeout value to `(5, None)` means that we're waiting 5 seconds for the connection to be established (which should be plenty enough), but we aren't setting a _read_ timeout (the actual time it takes for the operation to be performed on the manager).

CFY-7904 Remove HTTP/S read timeout from the cluster client

---

packaging/linux/provision.sh

On centos, nss (the ssl/tls lib used by curl & git) must be a recent
enough version to support tlsv1.2, so that we can connect to github.
As of 23.02.2018, github has dropped support for old tls versions
( https://github.com/blog/2507-weak-cryptographic-standards-removed )

build script: update nss

---

cloudify_cli/commands/deployments.py

avoid printing the same message twice when uploading a new blueprint in a specific tenant

CY-228 fix deployment update command log messaging

---

cloudify_cli/commands/agents.py

Because otherwise, it would be checked against old `install_new_agent`
workflow params (from old types.yaml files) and the execution will fail

CY-344 Don't pass the `stop_old_agent` param if it's false

---

cloudify_cli/cli/helptexts.py

Executions params should be between quotes otherwise the semicolon is handled by bash as the end of the command

Executions should include quotes

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/tests/commands/test_options.py

Allows `cfy agents list --node-id a --node-id b,c,d` to result in
node_ids=['a', 'b', 'c', 'd']

Allow agent filter options to be both multiple and comma-separated

---

cloudify_cli/commands/profiles.py

Instead of showing just the profile data which contains a single
manager_ip, if the current profile is a cluster profile, show
all stored nodes

CY-873 cfy profiles show: show cluster nodes

---

cloudify_cli/tests/resources/blueprints/bad_blueprint/blueprint_catalog.yaml

- Due to the naming limitation of the host agent name

CY-642: changing the namespace delimiter

---

cloudify_cli/commands/agents.py
cloudify_cli/tests/test_env.py

This allows using --stop-old-agents on deployments using an old
types.yaml

Agents install: allow_custom_parameters=True

---

cloudify_cli/commands/agents.py

So it doesn't shadow the builtin `list`, and cause any simple initialization like `my_list=list()` to completely screw things up.

Renamed function name

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/agents.py
cloudify_cli/tests/commands/test_agents.py

Fixed various issues with filtration logic and workflow execution logic.
The intention is to schedule the `install_new_agents` execution only for deployments that actually have node instances which match the filters.
Also, I removed the functionality of tracking the execution logs because it is impossible to interrupt using `SIGINT` (due to the use of threads). Instead, we tell the user which executions where scheduled for each affected deployment.

CY-1056: fixed multiple issues with agents install/validate

---

cloudify_cli/cli/helptexts.py

i.e. = id est = "that is" = used when clarifying something
e.g. = exempli gratia = "for example" = used when giving an example

Schedule execution helptext: s/i.e/e.g/

---

cloudify_cli/cli/cfy.py
cloudify_cli/commands/profiles.py
cloudify_cli/commands/ssl_cmd.py
cloudify_cli/tests/commands/test_profiles.py

It was available in `profiles use` but not in set.

CY-1868 Add --rest-port to `profiles set`

---

packaging/linux/provision.sh
packaging/windows/packaging/create_install_wizard.iss

- Prevent failing due to using an old mac version (10.12) and brew.
- Update to use ruby 2.5.0 version

CY-2148: fix mac cli build

---

cloudify_cli/commands/profiles.py

`cfy ssl enable` is supposed to just update the profile to enable ssl
It attempted to also do the equivalent of `cfy cluster update-profile`,
however that requires to contact the manager, and that isn't
necessarily possible (yet) because the manager might not have become
ssl (yet).
Anyway, we're updating the ssl setting for each manager. We're just
not updating the profile list (with any new managers that might
have been added in the meantime)
Alternatively we could've added a sleep, but just Not Doing It™
is simpler

CY-2249 `ssl enable`: don't update-profile with cluster nodes

---

cloudify_cli/cli/helptexts.py

The new description will be:
"Networks as a JSON string or as 'net1=ip1;net2=ip2'.
This argument can be used multiple times."

Fix the helptext of the networks option

---

cloudify_cli/commands/ssh.py
cloudify_cli/env.py
setup.py

For now, make the ssh subsystem an optional dependency.
This is so that the CLI can work with the current
cloudify-fabric-plugin.
This can/will possibly be reverted later, after the fabric-plugin
is ported, or after plugins are made to be installed
into separate virtualenvs.
For now, this should fix the build, anyway.

Make `cfy ssh` and fabric optional

---

cloudify_cli/commands/deployments.py

Not only for the deployment, but also for the execution

Deployment delete: ignore not found errors

---

cloudify_cli/commands/blueprints.py
cloudify_cli/commands/init.py
cloudify_cli/commands/maintenance_mode.py
cloudify_cli/commands/node_instances.py
cloudify_cli/commands/nodes.py
cloudify_cli/commands/workflows.py
cloudify_cli/env.py
cloudify_cli/inputs.py
cloudify_cli/table.py
cloudify_cli/tests/commands/test_install.py
cloudify_cli/tests/commands/test_node_instances.py
cloudify_cli/utils.py

See commit by commit.
Especially see what I think about things like decode_dict/decode_list:
functions like that are VERY WRONG, they go against the idea of the
"unicode sandwich" - if it's already a list/dict, it means it was already
loaded (from json, usually), so it should already be unicode. There is
NO REASON to go through a list and decode/encode every item in it.
That is the WRONG level to do it. The list should be first serialized
(json), and only after that, encoded.

CY-2456 Py3 porting: unicode changes

---

cloudify_cli/commands/plugins.py
cloudify_cli/tests/commands/test_plugins.py

Move a few things around, too.
Anyway, this formats the installation state into a `installed on`
column that says eg. "1 managers, 2 agents" or "3 managers, 5 errors"
etc.
Then, in `get`, it actually shows you the names.

CY-3302 Add installation state to plugin get/list

---

cloudify_cli/commands/plugins.py

Those columns are wrong, but apparently people are using them,
so let's keep them for backwards compat for now, and drop them in
the next version

plugins list: restore distribution & distribution_release columns

---

cloudify_cli/env.py

As opposed to urlsafe_b64encode.
No reason for this to be urlsafe. At all.
Also, urlsafe breaks, because flask uses the non-urlsafe version
when decoding: https://github.com/pallets/werkzeug/blob/bbc5cbb8390d8d9de4fff42456cab3d91b85b584/src/werkzeug/http.py#L622
(this is for making `request.authorization`, which we then use).
Also, the basic auth rfc (RFC 7617) talks about using the plain version
of base64, not an urlsafe variant.
It needs to be encoded the same way it's going to be decoded.

CY-3552 Use b64encode for creating credentials.

---

cloudify_cli/cli/cfy.py
cloudify_cli/commands/profiles.py

As the name suggests, this will now be the default tenant.
This allows `cfy profiles use` to run without `-t`, and it will
default to default_tenant.
Think of all the keypresses saved over the years.

CY-3580 Default --manager-tenant to default_tenant

---

cloudify_cli/execution_events_fetcher.py

In wait_for_execution, call fetch_process_events every loop,
and remove the condition.
The condition was wrong because:
- `not events_watcher.end_log_received`: this was not the case
when resuming an execution, which already had a "ended" log
before. The loop will be exited anyway, by the next `break`
- `execution.status != Execution.PENDING`: this is just unnecessary,
because this function is never really run for PENDING executions.
And if it was, let's fetch the events as we go, instead of
just silently iterating (yes, we would be iterating anyway!)

CY-3617 events list --tail: follow resumed executions

---

cloudify_cli/commands/agents.py
cloudify_cli/tests/commands/test_agents.py

Instead of limiting the node-instance list by deployment id,
just fetch all of them.
We can't put the list of deployments in the filters, because
those filters go into the rest call URL, and with thousands of
deployments, we easily hit the URL size limit.
Instead, let's just fetch _all_ the node instances. That approach
is obviously correct, even if wasteful.
It is "wasteful" because we will be fetching node instances even
for deployments that we have already filtered out by using
the --node-id filter.
This means that this approach is going to be doing unnecessary
requests, and will be slower, for `cfy agents install --node-id x`.
However, using --node-id alone, without --deployment-id is
a very rare, and not a very useful, usecase, that's why I'm not
worried about making it slower.
(and …

CY-3638 agent install: fetch all node-instances

---

cloudify_cli/commands/profiles.py

when switching profiles, we must not default the manager tenant,
otherwise the switch thinks the user provided a tenant name,
and logs a useless message about it.
Instead, only default it in the "create profile" branch of `use`.

CY-3641 cfy profiles use: only default the tenant name in the "create" path

---

cloudify_cli/commands/init.py
cloudify_cli/commands/profiles.py
cloudify_cli/constants.py
cloudify_cli/env.py
cloudify_cli/tests/__init__.py
cloudify_cli/tests/cfy.py
cloudify_cli/tests/commands/constants.py
cloudify_cli/tests/commands/test_profiles.py
cloudify_cli/tests/resources/profile.yaml
cloudify_cli/tests/test_env.py

Instead of storing the profile as yaml, store it as json.
Still allow loading old yaml files.
Also some refactors around the profile methods.
See each commit for details

CY-3678 Use JSON for the profile context file

---

cloudify_cli/env.py
cloudify_cli/tests/resources/profile.yaml

Support python/unicode because py2's yaml commonly generates those.
Still not gonna support the !CloudifyProfileContext via this,
because damn I'm not gonna rewrite yaml's whole dict parsing for this.

Load old profile yaml: support unicode tags

---

.circleci/config.yml
jenkins/Jenkinsfile
jenkins/build-pod.yaml
packaging/debian/build.sh

Setting the build to ubuntu, because we can't support debian
(debian stretch is py3.5, debian buster is py3.7)

Update the .deb build to use py3

---

cloudify_cli/replace_certificates_config.py

After the latest Prometheus related changes, we need to increase the retry times to get a healthy cluster status.

Increasing retry times for cluster status

---

cloudify_cli/cli/helptexts.py

The parameter is used to force plugin update on blueprints used (also) as components.

RD-872 Add --force parameter for cfy plugin update

---

cloudify_cli/utils.py

There's no .message, and it was deprecated in 2.6 anyway

RD-1281 Fix prettify_client_error for py3

---

packaging/cloudify-cli.spec
setup.py

The reason why we introduced this changes is because of in our build the Centos/Redhat started to fail because of lower version of pip used inside the .spec file. On the other hand, the latest version that is supported by python 2 is cryptography==3.3.2 and any higher version cannot be work with python2.   The cryptography library is a dependency  for paramiko which is in turn a dependency for fabric version on cloudify cli. The following error raised:
```
[2021-02-08T00:25:22.473Z] Collecting paramiko>=2.4 (from fabric==2.5.0->cloudify==5.3.0.dev1)
[2021-02-08T00:25:22.473Z]   Downloading https://files.pythonhosted.org/packages/95/19/124e9287b43e6ff3ebb9cdea3e5e8e88475a873c05ccdf8b7e20d2c4201e/paramiko-2.7.2-py2.py3-none-any.whl (206kB)
[2021-02-08T00:25:22.735Z] Collecting …
```

RD-1352 Pin cryptography version before installing fabric

---

cloudify_cli/cli/cfy.py
cloudify_cli/commands/blueprints.py
cloudify_cli/commands/deployments.py
cloudify_cli/tests/commands/test_blueprints.py

This PR adds filters to blueprints list.
The `filter` parameter was changed to `filter_rules` so it won't shadow the built-in name `filter`.

RD-1458 Add filters to blueprints list

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/deployments.py
cloudify_cli/tests/commands/test_deployments.py

* Add --auto-correct-types to deployments update
The flag can be used to trigger inputs type casting functionality
(a.k.a. inputs auto-correction) in the dsl_parser.

CYBL-1107-Automatically fix inputs' types

---

cloudify_cli/commands/plugins.py
cloudify_cli/tests/commands/test_plugins.py

* Add --auto-correct-types to plugins update
* Fix PluginsUpdateTest.test_all test
This is a cherry-pick of https://github.com/cloudify-cosmo/cloudify-cli/pull/1220 to the 5.1.3-build branch

RD-1515 Add --auto-correct-types to plugins update

---

cloudify_cli/commands/deployments.py

This PR created in order to expose the following deployment statuses: `installation_status` && `deployment_status` in the deployment table on the cli

RD-1482 Add deployment state to the deployment table info

---

cloudify_cli/commands/deployments.py

The `cloudify-execution-scheduler` service will always queue executions which can't run, so the `--queue` flag is useless
+ also fixes typos in the `summary` description

RD-1395 Remove the queue flag from schedule create CLI

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/plugins.py
cloudify_cli/tests/commands/test_plugins.py

The purpose of this modification is to provide the administrator with a tool to reconcile the statuses of plugins updates according to statuses of relevant executions.
The new `--reevaluate-active-statuses` will force reevaluation of active plugins-updates' statuses based on following scheme:
```
execution status | new plugins_update status
------------------+---------------------------
terminated       | successful
failed           | failed
cancelled        | failed
cancelling       | failed
force_cancelling | failed
kill_cancelling  | failed
```
Requires:
- https://github.com/cloudify-cosmo/cloudify-common/pull/699
- https://github.com/cloudify-cosmo/cloudify-manager/pull/2741

CYBL-1114 Reevaluate plugins update statuses

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/plugins.py
cloudify_cli/tests/commands/test_plugins.py

Add `--exclude-blueprint` parameter to the `cfy plugins update --all` command.  It's purpose is to skip update of specified blueprint(s).

RD-1638 Exclude blueprints from plugins update

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/plugins.py
cloudify_cli/tests/commands/test_plugins.py

* New flags for status reevaluation of plugins update
`-reevaluate-active-statuses` flag added to `cfy plugins update` command.
It's purpuse is to map the executions' statuses to plugin updates'
statuses before performing plugins update procedure.  `failed` and any
`*cancel*` statuses of the executions will be mapped to `failed` statuses
of the plugin updates, while `terminated` - to `successful`.
* Fix PluginsUpdateTest.test_all()
* Update helptext for reevaluate-active-status flag

CYBL-1114 reevaluate plugin and deployment update statuses

---

cloudify_cli/commands/blueprints.py
cloudify_cli/commands/plugins.py
cloudify_cli/commands/snapshots.py
cloudify_cli/tests/commands/test_blueprints.py
cloudify_cli/tests/commands/test_deployments.py
cloudify_cli/tests/commands/test_plugins.py
cloudify_cli/tests/commands/test_snapshots.py
cloudify_cli/utils.py

Currently, license validation happens only on the REST server. So when a user without an active license uploads a big file (blueprint, plugin, snapshot), then only after it has been uploaded (which takes a while) they get a message that there is no active license, and the operation fails. 
We'd like to spare users the wait by checking for an active license before upload commands are executed in the CLI.

RD-937 Add license validation wrapper to upload commands

---

cloudify_cli/cli/cfy.py

Parse the weekdays string when it is given by the user, in an option
callback. Then we can use structured data inside, instead of passing
just a string around.
cloudify-cosmo/cloudify-common#727 is the restclient side of this.
As a nice bonus, now you can do `--weekdays fr --weekdays su,mo` and
it will all be added together

RD-1603 Exec-schedules: split weekdays

---

cloudify_cli/filters_utils.py

Calling `cfy <resource> filters list` fails because the function `_filter_rules_to_string` tries to create `FilterRule` instances with the real operator and not the string version of it, e.g. `any_of` and not `any of`. To solve it, we should do the more reasonable thing which is changing the `FilterRule` `__init__` function to use the real operator, and the `to_string()` function to do the mapping from the string form of the operator to the real one.

Fix filters CLI

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/profiles.py
cloudify_cli/tests/commands/test_profiles.py

Allow changing just the IP for the current profile.
This is useful when the manager address changed, but we want to
keep all the other details unchanged (eg. the password).
This will be useful for the on-manager CLI, when restarting a manager
(container) with a changed address.

RD-1867 Add `--manager-ip` to `cfy prof set`

---

packaging/docker_builder/Dockerfile

Because of https://nvd.nist.gov/vuln/detail/CVE-2021-3156, let's use patched `sudo` RPM published by https://www.sudo.ws/.

RD-1908 Use patched sudo version 1.9.6

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/blueprints.py
cloudify_cli/commands/deployments.py
cloudify_cli/exceptions.py
cloudify_cli/filters_utils.py
cloudify_cli/labels_utils.py
cloudify_cli/tests/cfy.py
cloudify_cli/tests/commands/test_base.py
cloudify_cli/tests/commands/test_blueprints.py
cloudify_cli/tests/commands/test_deployments.py
cloudify_cli/tests/commands/test_filters.py
cloudify_cli/tests/commands/test_labels.py

If we want to allow special characters in labels, we need to modify the way they are currently provided in the CLI. This PR includes a few changes:
- Modifying the way we parse a provided labels list. This PR allows passing special characters in labels' values, where `,` and `:` must be escaped with `\`. 
- Modifying the way a user supplies filter rules. Following this PR, instead of supplying a string of filter rules separated by an ` and `, the user supplies each filter rule separately. This is done because I couldn't figure out a nice way to separate the big string of filter rules. 
- Moreover, the filter rules will be parsed using regular expressions to make sure we capture the right parts of each filter rule.
Associated PR: https://github.com/cloudify-cosmo/cloudify-manager/pull/2847

RD-1693 Allow special chars in labels

---

cloudify_cli/cli/cfy.py
cloudify_cli/commands/blueprints.py
cloudify_cli/commands/deployments.py
cloudify_cli/labels_utils.py
cloudify_cli/tests/commands/test_labels.py

Following a recent change we did to the labels' implementation to the CLI, https://github.com/cloudify-cosmo/cloudify-cli/pull/1264, we can now allow users to delete labels from a deployment by specifying a mixed list of labels and keys.

RD-1923 Change labels delete implementation

---

cloudify_cli/commands/executions.py

Until this patch logs were not displayed on a console after a user had
started a group execution.  This patch fixes that.

RD-1969 Include logs when waiting for execution group

---

cloudify_cli/commands/executions.py

The `@cfy.options.json_output` was not declared in function parameters
list which caused errors.  As we are not using this option, just drop
the lines.

Drop unused json_output option

---

cloudify_cli/commands/deployments.py

After https://github.com/cloudify-cosmo/cloudify-manager/pull/2922 we
are going to use labels to describe relationship between a service
(deployment) and an environment.

RD-2060 Use labels to describe relation with environment

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/deployments.py
cloudify_cli/tests/commands/test_deployments.py
dev-requirements.txt

This PR implements the following:
- Adding display name to deployments create.
- Adding `--generate-id` to deployments create.
- Adding `--search-name` to deployments list.

RD-2141 Add deployments display name

---

cloudify_cli/commands/executions.py

CLI for setting the target groups. See the docstring for what the
new commands actually do.

RD-1419 Exec-groups: set-success & set-failure

---

cloudify_cli/commands/executions.py

CLI for setting the target groups. See the docstring for what the
new commands actually do.

RD-1419 Exec-groups: set-success & set-failure, 6.0.0

---

cloudify_cli/commands/executions.py

The id is useful to have, I dont want to check `cfy exe gro li` every
time to find it

exec group start: add a log showing the exec-group id

---

cloudify_cli/utils.py

We want the blueprint state from AFTER the workflow finished, so we
must refetch it.
I note that the blueprint can be in an _intermediary_ failed state,
and then a retry (in the workflow) would save it. That's ugly and
we should probably change that, but for now, no need to return an
intermediary state to the user. Let's return the final state instead.
FWIW, the "retries" that save it happen in case of a cluster, where
the workflow sends a request to a restservice node who does not have
the blueprint, that restservice sets the blueprint state (ugly!),
and then the workflow (by using the cluster client) retries with
another restservice node, and then continues correctly.

RD-2485 wait_for_blueprint: refetch the bp before returning

---

cloudify_cli/tests/test_env.py

Ever since cloudify-cosmo/cloudify-common#795 we don't use raw
requests.get anymore, but create an explicit requests.Session.
So the mock that mocked requests.get, needs to be updated.

test_manager_offline: mock requests.Session

---

cloudify_cli/commands/users.py

Just warn. I don't want to error out on this, because then it's
a backwards-compat issue.

CY-3016 users create: warn if providing tenant role without a tenant

---

cloudify_cli/execution_events_fetcher.py
cloudify_cli/tests/test_env.py
cloudify_cli/utils.py

Events/logs are now sent in via REST, so it's synchronous wrt.
ordering vs the execution ending.
No need to wait the additional 3 seconds anymore!

RD-518 No need to wait for events after execution

---

jenkins/build-pod.yaml

Optimized QoS to burstable as some stages run in parallel use different containers.
Using spot NG wasn't enough resources as the tests starved for resources.
Optimizing the QoS keeps the build times about the same but makes sure the build won't choke the resources.

RD-2587 optimize qos

---

cloudify_cli/utils.py

Wait for upload_blueprint execution creation for maximum of about 5
seconds (0ms -> 100ms -> 200ms -> ... -> 900ms).  Sometimes the
execution was not started yet at the time we tried retrieving it's ID.

RD-3156 Wait for the upload_blueprint execution creation

---

cloudify_cli/cli/helptexts.py
cloudify_cli/commands/audit_log.py
cloudify_cli/utils.py

Truncate audit_log entries
```
Options:
-b, --before TEXT        Truncate audit logs which were stored this long ago
or earlier.  Can be specified either as the
difference counted from the current time (e.g. 6.5h
for 6:30 hours ago, 2d - 2 days ago, 7w - 7 weeks
ago), or an ordinary UTC timestamp (2021-08-18,
2021-08-18T14:25:36, 2021-08-18 14:25:36,
2021-08-18 14:25:36.99, @1629296736)  [required]
-c, --creator-name TEXT  Name of a user who introduced changes recorded in
the audit log.
-e, --execution-id TEXT  ID of an execution which introduced changes
recorded in the audit log.
```

RD-3089 Implement cfy auditlog truncate

---

jenkins/Jenkinsfile
packaging/debian/build.sh

Add gcc and python-dev to the .deb build, so that it can pass.
We need to be able to compile stuff, for some requirements.

Fix the DEB build

---

cloudify_cli/cli/cfy.py
cloudify_cli/commands/blueprints.py
cloudify_cli/local.py
jenkins/Jenkinsfile

I just did `cfy prof use local` and `cfy blu li` and was greeted with
an error. I expected to see an empty list instead.
So this makes it be an empty blueprints list indeed.

local: allow listing blueprints even if there's none

---

cloudify_cli/commands/plugins.py

Continue updating plugin even in case an update for a single blueprint
failed.

CYBL-1340 Handle errors during plugins update

---

cloudify_cli/commands/config.py

ever since cloudify-cosmo/cloudify-manager#3077 / RD-1580, restarting
the restservice is not required

config update message: no need to restart the restservice

---

cloudify_cli/commands/deployments.py

Also in json mode as well.
Currently we have no way of seeing the sub-deployment counts in
the CLI; this adds _a way_. So `cfy dep li -x` will show those columns.

In extended mode, show more deployment columns

---

setup.py

pin pynacl as 1.5.0 doesn't support py2.7 and it's collected from paramiko which is collected from fabric

pin pynacl to 1.4.0

---

cloudify_cli/commands/blueprints.py
cloudify_cli/commands/deployments.py
cloudify_cli/commands/secrets.py

Otherwise we cound not reach other tenant's objects (blueprints,
deployments, secrets).

RD-3239 Allow setting tenant when changing ownership

---

cloudify_cli/commands/blueprints.py
cloudify_cli/commands/deployments.py
cloudify_cli/labels_utils.py

`cfy blueprints get` failed for blueprints which had some labels defined.  This patch fixes that.
And also let's display information about plugins this blueprint has in its plan (because it's easy and can be helpful).

RD-3985 cfy blueprints get labels fix

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/deployments.py
cloudify_cli/commands/executions.py

So that we can update many deployments at a time.
Also factor out the flag, now that it's used in >1 places

Allow providing --concurrency for `cfy dep group update-deployments`

---

cloudify_cli/commands/executions.py
cloudify_cli/tests/commands/test_executions.py

Give the user a way to look at their operations and graphs. This is
going to give them more insight into their executions, and eg. what
operations caused an execution to fail.

RD-4292 CLI for listing operations/graphs

---

cloudify_cli/commands/profiles.py
cloudify_cli/env.py

If running `cfy profiles set` before `cfy profiles use`, then both `show-current` and the `set` command itself give uninformative errors (set before use gives `inet_pton() argument 2 must be str, not None` which is horrible). This PR fixes it

RD-4380 Fix uninformative errors in cfy profile set & show-current

---

cloudify_cli/commands/profiles.py

We check before saving anyway, and checking before processing
the new settings will run into interesting issues (e.g. when
trying to set a token while username and password are already set).

Don't check auth before setting profile settings 

---

cloudify_cli/commands/users.py

Okta users contain an @ which is blocked by the validation.

RD-4655 Allow deleting okta users

---

cloudify_cli/commands/workflows.py
cloudify_cli/tests/commands/test_workflows.py

When listing workflows, only show available ones by default, based
on the restservice response.
There's also a flag to show all of them

RD-4616 Hide unavailable workflows

---

cloudify_cli/commands/workflows.py
cloudify_cli/tests/commands/test_workflows.py

In the tabular output, just show names of the rules.
JSON can get the whole thing.

RD-4618 workflows list: show availability_rules

---

cloudify_cli/commands/nodes.py
cloudify_cli/logger.py

Add a shorthand to automatically run check_drift & check_staus
before showing the nodes list.
Also, I'm making json_output default to false to that logger
function. `--json-output` is deprecated anyway (replaced by just
the regular --json/--format=json)

RD-4990 Add `cfy nodes list --run-checks`

---

cloudify_cli/commands/nodes.py

Without deployment_id, the counts are always 0. No need to show
that, it's just misleading.
Maybe we should just deprecate or remove listing all nodes ever
(without a dep-id), it's not very useful.

nodes list: only show instance counts when dep_id is passed

---

cloudify_cli/commands/plugins.py

This applies to resource_tags, blueprint_labels and deployment_labels

Properly handle cases where no plugin metadata exist

---

cloudify_cli/commands/plugins.py
cloudify_cli/tests/commands/test_plugins.py

Just call the operation in the blueprint tenant's context

RD-5128 Fix `--all-tenants` functionality in plugins update

---

cloudify_cli/inputs.py
cloudify_cli/tests/commands/test_node_instances.py

Turns out `glob` here https://github.com/cloudify-cosmo/cloudify-cli/blob/535491cc4c2e7b803537928acdbf8eadda03ea88/cloudify_cli/inputs.py#L83 acts funny when parsing dicts, trying to read things like `m-3` as character ranges. Let's avoid it completely

RD-5234 Use JSON to read dict instead of glob

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/deployments.py

Allow an update that doesn't change the deployment itself, but will
still run
Presumably we'll have another, better, interface to run this later on,
but let's have one right now that allows actually running it at all.

RD-4466 Allow empty update

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/deployments.py

This will just skip the drift check. Duh.
The rest-client part of this is cloudify-cosmo/cloudify-common#1108

RD-4466 dep-up: add the skip-drift-check flag

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/deployments.py

This will make the changed nodes be just reinstalled, bypassing
the update interfaces

RD-4466 dep-up: add the force-reinstall flag

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/deployments.py

This is better because:
1. Talks about what will the update do
2. Doesn't include the word "update" in the flag (it's already
`cfy dep update`, right)
Also, product prefers this.

cfy dep update: rename --empty-update to --drift-only

---

cloudify_cli/commands/events.py

The API already supports filtering by those, let's just expose them
as arguments in the CLI! It's somewhat useful, because now I can
examine the logs of a very specific operation.
Also, I change the style first.

RD-5503 cfy events list: add --node and --operation filters

---

dev-requirements.txt
setup.py

Things that the cli doesn't DIRECTLY depend on, don't go in setup.py
Also no reason to pin wheel.
(no, Pinwheel is a Dark Souls 1 boss).

Remove unused libraries from setup.py

---

packaging/debian/build.sh

The other one was actually `Last-Modified: Mon, 19 Sep 2022 12:26:00 GMT`
This is the proper URL now, and I'm gonna hardcode x86_64 (ie. no aarch support here), because this already hardcodes amd64 in the control file.

debian build.sh: download the up-to-date python package

---

cloudify_cli/cli/cfy.py

Lowercasing everything is just a bad idea. This makes it impossible to pass some flags, eg `-T` (because it gets interpreted as `-t`)

RD-6220 Drop token_normalize_func

---

cloudify_cli/commands/cluster.py

Sometimes, one kind of a node just doesn't exist, and we don't want to throw a KeyError on that.
Specifically, right now in the separate-services deployment, we don't yet have the "manager" node declared.

Cluster profile: cope with nonexistent node types

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/agents.py
cloudify_cli/tests/commands/test_options.py

By default, `cfy agents list` only shows started agents; with this, it still does that, but CLI-side rather than restclient-side; and now it's also possible to list agents in other states.
Additionally, also show that state.

RD-6537 agents list: add `--all-states`

---

cloudify_cli/commands/executions.py

Allows changing concurrency for a group

RD-7042 Add client.execution_groups.set_concurrency

---

cloudify_cli/cli/cfy.py
cloudify_cli/cli/helptexts.py
cloudify_cli/commands/snapshots.py

It results in creating a legacy snapshot, i.e. based on a database dump
By default this parameter's value is set to `False` for Cloudify >= 7.1 and `True` for version 7.0.

RND-363 Add --legacy parameter for snapshot create

---

packaging/windows/win_cli_builder.ps1

Upgrade all the build tools so that things like cryptography can be installed via wheel

RND-681 windows build: update pip/wheel/setuptools

---

cloudify_cli/commands/deployments.py

`blueprint_id in kwargs` is not correct here, because with click, it's ALWAYS in kwargs, only sometimes it's None.
Ditto dont_update_plugins.
Also remove unused pass_context.

RND-862 `cfy dep gro update-deployments`: handle no blueprint id

---

cloudify_cli/commands/executions.py
requirements.txt

So we will retrieve only fields that we need to printout, which should decrease memory resources usage in case of big list of executions with a lot of data (like parameters for instance).

Limit response included fields for executions list
